baseURL = 'https://qskotlv.github.io/TestHugo.github.io/'
languageCode = 'en-us'
title = 'asdagn'
theme = 'm10c'


[[menu.main]]
  identifier = "tags"
  name = "jack"
  url = "/h/"
  
[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://www.bilibili.com/"
  
  